### ISSUE TITLE
Time for releasing code

### ISSUE THREAD

**Issue by CHMimilanlan** [yiyuzhuang/IDOL#1]
NICE WORK! 
I am really interested in it, and I am wondering when the code will be released?

**Comment by yiyuzhuang** [comment]
Thank you for your interest and kind words! We’re glad to hear you’re excited about our work. We’re working on finalizing everything and will release the code as soon as possible. 
Stay tuned!

**Comment by CHMimilanlan** [comment]
> Thank you for your interest and kind words! We’re glad to hear you’re excited about our work. We’re working on finalizing everything and will release the code as soon as possible. Stay tuned!

Hi, I have submit an application for getting dataset for a several days, and not get the access for dataset yet. I understand that you may be very busy, so please let me know if this is inconvenient or if you need more time to process my request. I will be grateful for your timely response!
